// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/ports_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	core "github.com/mo-pankaj/kctl/internal/core"
	gomock "go.uber.org/mock/gomock"
)

// MockContextManager is a mock of ContextManager interface.
type MockContextManager struct {
	ctrl     *gomock.Controller
	recorder *MockContextManagerMockRecorder
	isgomock struct{}
}

// MockContextManagerMockRecorder is the mock recorder for MockContextManager.
type MockContextManagerMockRecorder struct {
	mock *MockContextManager
}

// NewMockContextManager creates a new mock instance.
func NewMockContextManager(ctrl *gomock.Controller) *MockContextManager {
	mock := &MockContextManager{ctrl: ctrl}
	mock.recorder = &MockContextManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextManager) EXPECT() *MockContextManagerMockRecorder {
	return m.recorder
}

// Contexts mocks base method.
func (m *MockContextManager) Contexts() []core.ContextInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Contexts")
	ret0, _ := ret[0].([]core.ContextInfo)
	return ret0
}

// Contexts indicates an expected call of Contexts.
func (mr *MockContextManagerMockRecorder) Contexts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Contexts", reflect.TypeOf((*MockContextManager)(nil).Contexts))
}

// Current mocks base method.
func (m *MockContextManager) Current() core.ContextInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current")
	ret0, _ := ret[0].(core.ContextInfo)
	return ret0
}

// Current indicates an expected call of Current.
func (mr *MockContextManagerMockRecorder) Current() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockContextManager)(nil).Current))
}

// Use mocks base method.
func (m *MockContextManager) Use(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockContextManagerMockRecorder) Use(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockContextManager)(nil).Use), ctx, name)
}

// MockNamespaceLister is a mock of NamespaceLister interface.
type MockNamespaceLister struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceListerMockRecorder
	isgomock struct{}
}

// MockNamespaceListerMockRecorder is the mock recorder for MockNamespaceLister.
type MockNamespaceListerMockRecorder struct {
	mock *MockNamespaceLister
}

// NewMockNamespaceLister creates a new mock instance.
func NewMockNamespaceLister(ctrl *gomock.Controller) *MockNamespaceLister {
	mock := &MockNamespaceLister{ctrl: ctrl}
	mock.recorder = &MockNamespaceListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceLister) EXPECT() *MockNamespaceListerMockRecorder {
	return m.recorder
}

// Namespaces mocks base method.
func (m *MockNamespaceLister) Namespaces(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespaces", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Namespaces indicates an expected call of Namespaces.
func (mr *MockNamespaceListerMockRecorder) Namespaces(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespaces", reflect.TypeOf((*MockNamespaceLister)(nil).Namespaces), ctx)
}

// MockPodReader is a mock of PodReader interface.
type MockPodReader struct {
	ctrl     *gomock.Controller
	recorder *MockPodReaderMockRecorder
	isgomock struct{}
}

// MockPodReaderMockRecorder is the mock recorder for MockPodReader.
type MockPodReaderMockRecorder struct {
	mock *MockPodReader
}

// NewMockPodReader creates a new mock instance.
func NewMockPodReader(ctrl *gomock.Controller) *MockPodReader {
	mock := &MockPodReader{ctrl: ctrl}
	mock.recorder = &MockPodReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodReader) EXPECT() *MockPodReaderMockRecorder {
	return m.recorder
}

// Logs mocks base method.
func (m *MockPodReader) Logs(ctx context.Context, req core.LogRequest) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logs", ctx, req)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logs indicates an expected call of Logs.
func (mr *MockPodReaderMockRecorder) Logs(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logs", reflect.TypeOf((*MockPodReader)(nil).Logs), ctx, req)
}

// Pod mocks base method.
func (m *MockPodReader) Pod(ctx context.Context, ns, name string) (*core.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pod", ctx, ns, name)
	ret0, _ := ret[0].(*core.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pod indicates an expected call of Pod.
func (mr *MockPodReaderMockRecorder) Pod(ctx, ns, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pod", reflect.TypeOf((*MockPodReader)(nil).Pod), ctx, ns, name)
}

// Pods mocks base method.
func (m *MockPodReader) Pods(ctx context.Context, sel core.Selector) ([]core.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pods", ctx, sel)
	ret0, _ := ret[0].([]core.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pods indicates an expected call of Pods.
func (mr *MockPodReaderMockRecorder) Pods(ctx, sel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pods", reflect.TypeOf((*MockPodReader)(nil).Pods), ctx, sel)
}

// Subscribe mocks base method.
func (m *MockPodReader) Subscribe(ctx context.Context, sel core.Selector) (<-chan struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, sel)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockPodReaderMockRecorder) Subscribe(ctx, sel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockPodReader)(nil).Subscribe), ctx, sel)
}

// MockPodDescriber is a mock of PodDescriber interface.
type MockPodDescriber struct {
	ctrl     *gomock.Controller
	recorder *MockPodDescriberMockRecorder
	isgomock struct{}
}

// MockPodDescriberMockRecorder is the mock recorder for MockPodDescriber.
type MockPodDescriberMockRecorder struct {
	mock *MockPodDescriber
}

// NewMockPodDescriber creates a new mock instance.
func NewMockPodDescriber(ctrl *gomock.Controller) *MockPodDescriber {
	mock := &MockPodDescriber{ctrl: ctrl}
	mock.recorder = &MockPodDescriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodDescriber) EXPECT() *MockPodDescriberMockRecorder {
	return m.recorder
}

// Describe mocks base method.
func (m *MockPodDescriber) Describe(ctx context.Context, ns, name string) (*core.PodDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Describe", ctx, ns, name)
	ret0, _ := ret[0].(*core.PodDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Describe indicates an expected call of Describe.
func (mr *MockPodDescriberMockRecorder) Describe(ctx, ns, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Describe", reflect.TypeOf((*MockPodDescriber)(nil).Describe), ctx, ns, name)
}

// Events mocks base method.
func (m *MockPodDescriber) Events(ctx context.Context, ns, name string) ([]core.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, ns, name)
	ret0, _ := ret[0].([]core.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockPodDescriberMockRecorder) Events(ctx, ns, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockPodDescriber)(nil).Events), ctx, ns, name)
}
